### ISSUE TITLE
Component > Styling > Mission > Move Arrow1.svg to another directory

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#36]
## Is your feature request related to a problem? Please describe.
Assets should not be in the same folder as the component, this should be with the rest of the assets in `public/assets`

## Describe the solution you'd like
Move the file to the appropriate location and update any references.

**Comment by cvalencia1991** [comment]
hello everyone, i think that the solution that you say its correct but i think `public/assets` are not the file that could implement, it could be `public/images` because SVG are images, by the way you can assign me for this @JacobHeldt

**Comment by JacobHeldt** [comment]
I'd prefer moving the SVG file to the assets folder for now, since all of our images and SVGs are currently stored there. However, I'm open to discussing the possibility of creating a new issue later that moves all SVGs into an images folder. For this particular issue, I believe it would be better to store the SVG file in the `public/assets` folder.

**Comment by cvalencia1991** [comment]
this issue can be closed
